import type { NextPage, GetStaticProps } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import imageLoader from "../imageLoader";
import styles from "../styles/Home.module.css";
import { Result, Welcome } from "../types";

const Home: NextPage<{ data: Result[] }> = ({ data }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {data.map((item) => {
        return (
          <div key={item.id}>
            <li>
              <Link href={`/data/${item.id}`}>
                <a>{item.name}</a>
              </Link>
            </li>
            <Image
              loader={imageLoader}
              unoptimized
              src={item.image}
              alt={item.name}
              width="200"
              height="200"
            />
          </div>
        );
      })}
    </div>
  );
};

export const getStaticProps: GetStaticProps = async (context) => {
  const res = await fetch("https://rickandmortyapi.com/api/character");
  const { results }: Welcome = await res.json();
  return {
    props: {
      data: results,
    },
  };
};

export default Home;
